let ru = {
  "menu_add_book_title": "Добавить книгу",
  "menu_my_books_title": "Мои книги",
  "menu_books_title": "Книги",
  "menu_readers_title": "Читатели",
  "menu_favorite_title": "Избранные",
  "menu_favorite_readers_title": "Читатели",
  "favorite_readers_title": "Избранные читатели",
  "logo_title": "Бубук",

  "register_page_title": "Бубук - Регистрация",
  "register_form_title": "Создать аккаунт",
  "register_name_title": "Имя",
  "register_email_title": "Электронная почта",
  "register_password_title": "Пароль",
  "register_register_button_title": "Создать",
  "register_login_button_title": "Войти",
  "register_close_title": "Закрыть",

  "login_page_title": "Бубук - Вход",
  "login_login_form_title": "Вход",
  "login_email_title": "Электронная почта",
  "login_password_title": "Пароль",
  "login_register_button_title": "Создать",
  "login_login_button_title": "Войти",

  "cabinet_page_title": "Бубук - Кабинет читателя",
  "chat_title": "Сообщения",
  "profile_title": "Мой профиль",
  "logout_title": "Выйти",

  "add_book_title": "Добавить книгу",
  "book_title_title": "Название ",
  "author_name_title": "Имя автора ",
  "author_surname_title": "Фамилия автора ",
  "publisher_title": "Издательство",
  "year_title": "Год",
  "pages_quantity_title": "Страниц",

  "language_title": "Язык",
  "language_select_title": "выбрать",
  "language_rus_title": "русский",
  "language_ukr_title": "украинский",
  "language_eng_title": "английский",
  "language_oth_title": "другой",

  "cover_title": "Обложка",
  "select_cover_title": "выбрать",
  "select_hard_title": "твёрдая",
  "select_soft_title": "мягкая",

  "illustrations_title": "Иллюстрации",
  "select_illustrations_title": "выбрать",
  "select_illustrations_no_title": "нет",
  "select_illustrations_bw_title": "чёрно-белые",
  "select_illustrations_color_title": "цветные",

  "age_group_title": "Возрастная группа",
  "select_age_title": "выбрать",
  "select_age_baby_title": "малыши",
  "select_age_preschool_title": "дошкольники",
  "select_age_junior_title": "младшие школьники",
  "select_age_midschool_title": "подростки",
  "select_age_adult_title": "взрослые",

  "description_title": "Описание",
  "images_description_title": "Хорошо добавить: обложку, страницу с иллюстрацией, страницу с текстом и несколько, которые вам нравятся",
  "fileButton": "Добавить фото",
  "add_book_close_title": "Закрыть",
  "add_book_button_title": "Добавить книгу",

  //
  "edit_book_modal_title": "Редактировать книгу",
  "edit_book_title_title": "Название ",
  "edit_book_active_title": "Активная",
  "edit_book_active_yes": "да",
  "edit_book_active_no": "нет",

  "edit_book_author_name_title": "Имя автора ",
  "edit_book_author_surname_title": "Фамилия автора ",
  "edit_book_publisher_title": "Издательство",
  "edit_book_year_title": "Год",
  "edit_book_pages_quantity_title": "Страниц",

  "edit_book_language_title": "Язык",
  "edit_book_language_select_title": "выбрать",
  "edit_book_language_rus_title": "русский",
  "edit_book_language_ukr_title": "украинский",
  "edit_book_language_eng_title": "английский",
  "edit_book_language_oth_title": "другой",

  "edit_book_cover_title": "Обложка",
  "edit_book_select_cover_title": "выбрать",
  "edit_book_select_hard_title": "твёрдая",
  "edit_book_select_soft_title": "мягкая",

  "edit_book_illustrations_title": "Иллюстрации",
  "edit_book_select_illustrations_title": "выбрать",
  "edit_book_select_illustrations_no_title": "нет",
  "edit_book_select_illustrations_bw_title": "чёрно-белые",
  "edit_book_select_illustrations_color_title": "цветные",

  "edit_book_age_group_title": "Возрастная группа",
  "edit_book_select_age_title": "выбрать",
  "edit_book_select_age_baby_title": "малыши",
  "edit_book_select_age_preschool_title": "дошкольники",
  "edit_book_select_age_junior_title": "младшие школьники",
  "edit_book_select_age_midschool_title": "подростки",
  "edit_book_select_age_adult_title": "взрослые",

  "edit_book_description_title": "Описание",
  "edit_book_images_description_title": "Хорошо добавить: обложку, страницу с иллюстрацией, страницу с текстом и несколько, которые вам нравятся",
  "edit_fileButton": "Добавить фото",
  "edit_book_close_title": "Закрыть",
  "edit_book_button_title": "Сохранить",

  "details_edit_book_button_title": "Редактировать",
  "details_set_inactive_button_title": "Деактивировать",
  "details_set_active_button_title": "Активировать",
  "details_delete_button_title": "Удалить",
  "details_inactive_title": "НЕАКТИВНАЯ",
  "details_publisher_title": "Издательство: ",
  "details_language_title": "Язык: ",
  "details_year_title": "Год: ",
  "details_cover_title": "Обложка: ",
  "details_illustrations_title": "Иллюстрации: ",
  "details_ageGroup_title": "Возраст: ",
  "details_pages_title": "Страниц: ",
  "details_description_title": "Описание: ",

  "search_book_title_title": "Название",
  "search_book_author_name_title": "Имя автора",
  "search_book_author_surname_title": "Фамилия автора",
  "search_book_city_title": "Город",
  "search_book_age_from_title": "От возрастной группы",
  "search_book_age_to_title": "До возрастной группы ",
  "search_book_year_from_title": "От года",
  "search_book_year_to_title": "До года",
  "search_button_title": "Искать",
  "doNotDelete_warning_title": "Если вы не хотите, чтобы другие читатели видели эту книгу, достаточно её деактивировать",
  "doYouStillWantToDelete_title": "Всё равно хотите удалить?",
  "book_title": "Книга ",
  "hasBeenDeleted_title": " была успешно удалена",
  "hasBeenSetActive_title": " теперь активна",
  "hasBeenSetInactive_title": " теперь неактивна",
  "cannotBeEdited_title": " не может быть изменена",
  "hasBeenEdited_title": " была успешно изменена",
  "cannotBeAdded_title": " не может быть добавлена",
  "hasBeenAdded_title": " была успешно добавлена",
  "noBookWasFound_title": "По вашему запросу не было найдено ни одной книги. Может, попробуете смягчить критерии?",
  "goodDayToStartAddingBooks_title": "Сегодня - отличный день, чтобы начать добавлять книги",


  "recent_title": "Недавние"
}


let ua = {
  "menu_add_book_title": "Додати книгу",
  "menu_my_books_title": "Мої книги",
  "menu_books_title": "Книги",
  "menu_readers_title": "Читачі",
  "menu_favorite_title": "Улюблені",
  "menu_favorite_readers_title": "Читачі",
  "favorite_readers_title": "Улюблені читачі",
  "logo_title": "Бубук",

  "register_page_title": "Бубук - Реєстрацiя",
  "register_form_title": "Створити акаунт",
  "register_name_title": "Им'я",
  "register_email_title": "Електронная пошта",
  "register_password_title": "Пароль",
  "register_register_button_title": "Створити",
  "register_login_button_title": "Увiйти",
  "register_close_title": "Закрити",

  "login_page_title": "Бубук - Вхiд",
  "login_login_form_title": "Вхiд",
  "login_email_title": "Електронна пошта",
  "login_password_title": "Пароль",
  "login_register_button_title": "Створити",
  "login_login_button_title": "Увiйти",

  "cabinet_page_title": "Бубук - Кабiнет читача",
  "chat_title": "Повідомлення",
  "profile_title": "Мій профіль",
  "logout_title": "Вийти",

  "add_book_title": "Додати книгу",
  "book_title_title": "Назва ",
  "author_name_title": "Ім'я автора ",
  "author_surname_title": "Прізвище автора ",
  "publisher_title": "Видавництво",
  "year_title": "Рік",
  "pages_quantity_title": "Сторінок",

  "language_title": "Мова",
  "language_select_title": "обрати",
  "language_rus_title": "росiйська",
  "language_ukr_title": "українська",
  "language_eng_title": "англійська",
  "language_oth_title": "iнша",

  "cover_title": "Обкладинка",
  "select_cover_title": "обрати",
  "select_hard_title": "тверда",
  "select_soft_title": "м'яка",

  "illustrations_title": "Ілюстрації",
  "select_illustrations_title": "обрати",
  "select_illustrations_no_title": "вiдсутнi",
  "select_illustrations_bw_title": "чорно-бiлi",
  "select_illustrations_color_title": "кольоровi",

  "age_group_title": "Вікова категорія",
  "select_age_title": "обрати",
  "select_age_baby_title": "малюки",
  "select_age_preschool_title": "дошкільнята",
  "select_age_junior_title": "молодші школярі",
  "select_age_midschool_title": "пiдлiтки",
  "select_age_adult_title": "дорослі",

  "description_title": "Опис",
  "images_description_title": "Гарно додати: обкладинку, сторiнку з iлюстрацiєю, сторiнку з текстом та декiлька, що вам до вподоби",
  "fileButton": "Додати фото",
  "add_book_close_title": "Закрити",
  "add_book_button_title": "Додати книгу",

  "edit_book_modal_title": "Редагувати книгу",
  "edit_book_title_title": "Назва ",
  "edit_book_active_title": "Активна",
  "edit_book_active_yes": "так",
  "edit_book_active_no": "нi",

  "edit_book_author_name_title": "Ім'я автора ",
  "edit_book_author_surname_title": "Прізвище автора ",
  "edit_book_publisher_title": "Видавництво",
  "edit_book_year_title": "Рік",
  "edit_book_pages_quantity_title": "Сторінок",

  "edit_book_language_title": "Мова",
  "edit_book_language_select_title": "обрати",
  "edit_book_language_rus_title": "росiйська",
  "edit_book_language_ukr_title": "українська",
  "edit_book_language_eng_title": "англійська",
  "edit_book_language_oth_title": "iнша",

  "edit_book_cover_title": "Обкладинка",
  "edit_book_select_cover_title": "обрати",
  "edit_book_select_hard_title": "тверда",
  "edit_book_select_soft_title": "м'яка",

  "edit_book_illustrations_title": "Ілюстрації",
  "edit_book_select_illustrations_title": "обрати",
  "edit_book_select_illustrations_no_title": "вiдсутнi",
  "edit_book_select_illustrations_bw_title": "чорно-бiлi",
  "edit_book_select_illustrations_color_title": "кольоровi",

  "edit_book_age_group_title": "Вікова категорія",
  "edit_book_select_age_title": "обрати",
  "edit_book_select_age_baby_title": "малюки",
  "edit_book_select_age_preschool_title": "дошкільнята",
  "edit_book_select_age_junior_title": "молодші школярі",
  "edit_book_select_age_midschool_title": "пiдлiтки",
  "edit_book_select_age_adult_title": "дорослі",

  "edit_book_description_title": "Опис",
  "edit_book_images_description_title": "Гарно додати: обкладинку, сторiнку з iлюстрацiєю, сторiнку з текстом та декiлька, що вам до вподоби",
  "edit_fileButton": "Додати фото",
  "edit_book_close_title": "Закрити",
  "edit_book_button_title": "Зберегти",

  "details_edit_book_button_title": "Редагувати",
  "details_set_inactive_button_title": "Приховати",
  "details_set_active_button_title": "Показати",
  "details_delete_button_title": "Видалити",
  "details_inactive_title": "НЕАКТИВНА",
  "details_publisher_title": "Видавництво: ",
  "details_language_title": "Мова: ",
  "details_year_title": "Рік: ",
  "details_cover_title": "Обкладинка: ",
  "details_illustrations_title": "Ілюстрації: ",
  "details_ageGroup_title": "Вік читача: ",
  "details_pages_title": "Сторінок: ",
  "details_description_title": "Опис: ",

  "search_book_title_title": "Назва",
  "search_book_author_name_title": "Ім'я автора",
  "search_book_author_surname_title": "Прізвище автора",
  "search_book_city_title": "Місто",
  "search_book_age_from_title": "Від віку",
  "search_book_age_to_title": "До віку",
  "search_book_year_from_title": "Від року",
  "search_book_year_to_title": "До року",
  "search_button_title": "Шукати",
  "doNotDelete_warning_title": "Якщо ви не хочете, аби інші читачі бачили цю книгу, достатьо її деактивувати",
  "doYouStillWantToDelete_title": "Все рівно хочете видалити?",
  "book_title": "Книга ",
  "hasBeenDeleted_title": " була успішно видалена",
  "hasBeenSetActive_title": " наразі активна",
  "hasBeenSetInactive_title": " наразі неактивна",
  "cannotBeEdited_title": " не може бути зміненою",
  "hasBeenEdited_title": " була успішно змінена",
  "cannotBeAdded_title": " не може бути доданою",
  "hasBeenAdded_title": " була успішно додана",
  "noBookWasFound_title": "За вашим запитом не було знайдено жодної книги. Може, спробувати пом'ягшити критерії?",
  "goodDayToStartAddingBooks_title": "Сьогодні - чудовий день, аби почати додавати книжки",


  "recent_title": "Нещодавні"
}

let en = {
  "menu_add_book_title": "Add book",
  "menu_my_books_title": "My books",
  "menu_books_title": "Books",
  "menu_readers_title": "Readers",
  "menu_favorite_title": "Favorite",
  "menu_favorite_readers_title": "Readers",
  "favorite_readers_title": "Favorite Readers",
  "logo_title": "BooBook",

  "register_page_title": "BooBook - Register Page",
  "register_form_title": "Create an account", //not
  "register_name_title": "First name",
  "register_email_title": "Email address",
  "register_password_title": "Password",
  "register_register_button_title": "Register",
  "register_login_button_title": "Login",
  "register_close_title": "Close",

  "login_page_title": "BooBook - Login Page",
  "login_login_form_title": "Login",
  "login_email_title": "Email address",
  "login_password_title": "Password",
  "login_register_button_title": "Register",
  "login_login_button_title": "Login",

  "cabinet_page_title": "BooBook - Reader's Cabinet",
  "chat_title": "Chat",
  "profile_title": "Profile",
  "logout_title": "Log Out",

  "add_book_title": "Add book",
  "book_title_title": "Title ",
  "author_name_title": "Author Name ",
  "author_surname_title": "Author Surname ",
  "publisher_title": "Publisher",
  "year_title": "Year",
  "pages_quantity_title": "Pages quantity",

  "language_title": "Language",
  "language_select_title": "select",
  "language_rus_title": "russian",
  "language_ukr_title": "ukrainian",
  "language_eng_title": "english",
  "language_oth_title": "other",

  "cover_title": "Cover",
  "select_cover_title": "select",
  "select_hard_title": "hard",
  "select_soft_title": "soft",

  "illustrations_title": "Illustrations",
  "select_illustrations_title": "select",
  "select_illustrations_no_title": "no",
  "select_illustrations_bw_title": "black & white",
  "select_illustrations_color_title": "color",

  "age_group_title": "Age group",
  "select_age_title": "select",
  "select_age_baby_title": "baby",
  "select_age_preschool_title": "preschool",
  "select_age_junior_title": "junior-school",
  "select_age_midschool_title": "mid-school",
  "select_age_adult_title": "adult",

  "description_title": "Description",
  "images_description_title": "Images are recommended to include: cover, one with text, one with illustration, and others you like",
  "fileButton": "Select images",
  "add_book_close_title": "Close",
  "add_book_button_title": "Add book",

  "edit_book_modal_title": "Edit book",
  "edit_book_title_title": "Title ",
  "edit_book_active_title": "Active",
  "edit_book_active_yes": "yes",
  "edit_book_active_no": "no",

  "edit_book_author_name_title": "Author Name ",
  "edit_book_author_surname_title": "Author Surname ",
  "edit_book_publisher_title": "Publisher",
  "edit_book_year_title": "Year",
  "edit_book_pages_quantity_title": "Pages quantity",

  "edit_book_language_title": "Language",
  "edit_book_language_select_title": "select",
  "edit_book_language_rus_title": "russian",
  "edit_book_language_ukr_title": "ukrainian",
  "edit_book_language_eng_title": "english",
  "edit_book_language_oth_title": "other",

  "edit_book_cover_title": "Cover",
  "edit_book_select_cover_title": "select",
  "edit_book_select_hard_title": "hard",
  "edit_book_select_soft_title": "soft",

  "edit_book_illustrations_title": "Illustrations",
  "edit_book_select_illustrations_title": "select",
  "edit_book_select_illustrations_no_title": "no",
  "edit_book_select_illustrations_bw_title": "black & white",
  "edit_book_select_illustrations_color_title": "color",

  "edit_book_age_group_title": "Age group",
  "edit_book_select_age_title": "select",
  "edit_book_select_age_baby_title": "baby",
  "edit_book_select_age_preschool_title": "preschool",
  "edit_book_select_age_junior_title": "junior-school",
  "edit_book_select_age_midschool_title": "mid-school",
  "edit_book_select_age_adult_title": "adult",

  "edit_book_description_title": "Description",
  "edit_book_images_description_title": "Images are recommended to include: cover, one with text, one with illustration, and others you like",
  "edit_fileButton": "Select images",
  "edit_book_close_title": "Close",
  "edit_book_button_title": "Save",

  "details_edit_book_button_title": "Edit",
  "details_set_inactive_button_title": "Set inactive",
  "details_set_active_button_title": "Set active",
  "details_delete_button_title": "Delete",
  "details_inactive_title": "INACTIVE",
  "details_publisher_title": "Publisher: ",
  "details_language_title": "Language: ",
  "details_year_title": "Year: ",
  "details_cover_title": "Cover: ",
  "details_illustrations_title": "Illustrations: ",
  "details_ageGroup_title": "Age group: ",
  "details_pages_title": "Pages: ",
  "details_description_title": "Description: ",

  "search_book_title_title": "Title",
  "search_book_author_name_title": "Author name",
  "search_book_author_surname_title": "Author surname",
  "search_book_city_title": "City",
  "search_book_age_from_title": "Age group from",
  "search_book_age_to_title": "Age group to",
  "search_book_year_from_title": "Year from",
  "search_book_year_to_title": "Year to",
  "search_button_title": "Search",
  "doNotDelete_warning_title": "If you do not want others to see this book, you can make it Inactive.",
  "doYouStillWantToDelete_title": "Do you still want to delete book ",
  "book_title": "Book ",
  "hasBeenDeleted_title": " has been deleted",
  "hasBeenSetActive_title": " has been set active",
  "hasBeenSetInactive_title": " has been set inactive",
  "cannotBeEdited_title": " cannot be edited",
  "hasBeenEdited_title": " has been successfully edited",
  "cannotBeAdded_title": " cannot be added",
  "hasBeenAdded_title": " has been successfully added",
  "noBookWasFound_title": "No book fitting your criteria was found. Try to soften the borders",
  "goodDayToStartAddingBooks_title": "Today is a good day to start adding books.",


  "recent_title": "Recent"
}




let application_language = en;
