let ru = {
  "menu_add_book_title": "Добавить книгу",
  "menu_my_books_title": "Мои книги",
  "menu_books_title": "Книги",
  "menu_readers_title": "Читатели",
  "menu_favorite_title": "Избранные",
  "menu_favorite_readers_title": "Читатели",
  "logo_title": "Бубук",
  "login_page_title": "Бубук - Вход",
  "register_page_title": "Бубук - Регистрация",
  "cabinet_page_title": "Бубук - Кабинет читателя",
  "login_form_title": "Вход",
  "register_form_title": "Создать аккаунт",
  "register_name": "Имя",
  "email": "Электронная почта",
  "password": "Пароль",
  "register": "Зарегистрироваться",
  "login": "Войти",
  "close": "Закрыть",
  "chat_title": "Сообщения",
  "profile_title": "Мой профиль",
  "logout_title": "Выйти",
  "add_book_title": "Добавить книгу",
  "book_title_title": "Название ",
  "author_name_title": "Имя автора ",
  "author_surname_title": "Фамилия автора ",
  "publisher_title": "Издательство",
  "year_title": "Год",
  "pages_quantity_title": "Страниц",
  "language_title": "Язык",
  "select_title": "выбрать",
  "select_cover_title": "выбрать",
  "select_illustrations_title": "выбрать",
  "select_age_title": "выбрать",
  "cover_title": "Обложка",
  "illustrations_title": "Иллюстрации",
  "age_group_title": "Возраст",
  "recent_title": "Недавние"

}

let en = {
  "menu_add_book_title": "Add book",
  "menu_my_books_title": "My books",
  "menu_books_title": "Books",
  "menu_readers_title": "Readers",
  "menu_favorite_title": "Favorite",
  "menu_favorite_readers_title": "Readers",
  "logo_title": "BooBook",
  "login_page_title": "BooBook - Login Page", //not
  "register_page_title": "BooBook - Register Page",
  "cabinet_page_title": "BooBook - Reader's Cabinet",
  "login_form_title": "Login",
  "register_form_title": "Create an account",
  "register_name": "First name",
  "email": "Email address",
  "password": "Password",
  "register": "Register",
  "login": "Login",
  "close": "Close",//not
  "chat_title": "Chat",
  "profile_title": "Profile",
  "logout_title": "Log Out",
  "add_book_title": "Add book",
  "book_title_title": "Title ",
  "author_name_title": "Author Name ",
  "author_surname_title": "Author Surname ",
  "publisher_title": "Publisher",
  "year_title": "Year",
  "pages_quantity_title": "Pages quantity",
  "language_title": "Language",
  "select_title": "select",
  "select_cover_title": "select",
  "select_illustrations_title": "select",
  "select_age_title": "select",
  "cover_title": "Cover",
  "illustrations_title": "Illustrations",
  "age_group_title": "Age group",
  "recent_title": "Recent" //not
}


let ua = {
  "menu_add_book_title": "Додати книгу",
  "menu_my_books_title": "Мої книги",
  "menu_books_title": "Книги",
  "menu_readers_title": "Читачі",
  "menu_favorite_title": "Улюблені",
  "menu_favorite_readers_title": "Читачі",
  "logo_title": "Бубук",
  "login_page_title": "Бубук - Вхiд",
  "register_page_title": "Бубук - Ре/'страц/'я",
  "cabinet_page_title": "Бубук - Кабiнет читача",
  "login_form_title": "Вхiд",
  "register_form_title": "Створити акаунт",
  "register_name": "Им/'я",
  "email": "Електронна пошта",
  "password": "Пароль",
  "register": "Зареєструватися",
  "login": "Увiйти",
  "close": "Закрити",
  "chat_title": "Повідомлення",
  "profile_title": "Мій профіль",
  "logout_title": "Вийти",
  "add_book_title": "Додати книгу",
  "book_title_title": "Назва ",
  "author_name_title": "Ім/'я автора ",
  "author_surname_title": "Прізвище автора ",
  "publisher_title": "Видавництво",
  "year_title": "Рік",
  "pages_quantity_title": "Сторінок",
  "language_title": "Мова",
  "select_title": "обрати",
  "select_cover_title": "обрати",
  "select_illustrations_title": "обрати",
  "select_age_title": "обрати",
  "cover_title": "Обкладинка",
  "illustrations_title": "Ілюстрації",
  "age_group_title": "Вік читача",
  "recent_title": "Нещодавні"
}


let application_language = en;
