let ru = {
    "menu_add_book_title": "Добавить книгу",
    "menu_my_books_title": "Мои книги",
    "menu_books_title": "Книги",
    "menu_readers_title": "Читатели",
    "menu_favorite_title": "Избранные",
    "menu_favorite_readers_title": "Читатели",
    "favorite_readers_title": "Избранные читатели",
    "logo_title": "Бубук",
    "add_reader_to_favorites_title": "Добавить читателя в избранные",
    "remove_reader_from_favorites_title": "Удалить читателя из избранных",
    "send_message_title": "Отправить сообщение",

    "register_page_title": "Бубук - Регистрация",
    "register_form_title": "Создать аккаунт",
    "register_name_title": "Имя",
    "register_email_title": "Электронная почта",
    "register_password_title": "Пароль",
    "register_register_button_title": "Создать",
    "register_login_button_title": "Войти",
    "register_close_title": "Закрыть",

    "login_page_title": "Бубук - Вход",
    "login_login_form_title": "Вход",
    "login_email_title": "Электронная почта",
    "login_password_title": "Пароль",
    "login_register_button_title": "Создать",
    "login_login_button_title": "Войти",

    "cabinet_page_title": "Бубук - Кабинет читателя",
    "chat_title": "Сообщения",
    "profile_title": "Мой профиль",
    "logout_title": "Выйти",

    "add_book_title": "Добавить книгу",
    "book_title_title": "Название ",
    "author_name_title": "Имя автора ",
    "author_surname_title": "Фамилия автора ",
    "publisher_title": "Издательство",
    "year_title": "Год",
    "pages_quantity_title": "Страниц",

    "language_title": "Язык",
    "language_select_title": "выбрать",
    "language_rus_title": "русский",
    "language_ukr_title": "украинский",
    "language_eng_title": "английский",
    "language_oth_title": "другой",

    "cover_title": "Обложка",
    "select_cover_title": "выбрать",
    "select_hard_title": "твёрдая",
    "select_soft_title": "мягкая",

    "illustrations_title": "Иллюстрации",
    "select_illustrations_title": "выбрать",
    "select_illustrations_no_title": "нет",
    "select_illustrations_bw_title": "чёрно-белые",
    "select_illustrations_color_title": "цветные",

    "age_group_title": "Возрастная группа",
    "select_age_title": "выбрать",
    "select_age_baby_title": "малыши",
    "select_age_preschool_title": "дошкольники",
    "select_age_junior_title": "младшие школьники",
    "select_age_midschool_title": "подростки",
    "select_age_adult_title": "взрослые",

    "description_title": "Описание",
    "images_description_title": "Рекомендуем добавить обложку, страницу с иллюстрацией, страницу с текстом и остальные на ваш выбор.",
    "fileButton": "Добавить фото",
    "add_book_close_title": "Закрыть",
    "add_book_button_title": "Добавить книгу",

    "edit_book_modal_title": "Редактировать книгу",
    "edit_book_title_title": "Название ",
    "edit_book_active_title": "Активная",
    "edit_book_active_yes": "да",
    "edit_book_active_no": "нет",

    "edit_book_author_name_title": "Имя автора ",
    "edit_book_author_surname_title": "Фамилия автора ",
    "edit_book_publisher_title": "Издательство",
    "edit_book_year_title": "Год",
    "edit_book_pages_quantity_title": "Страниц",

    "edit_book_language_title": "Язык",
    "edit_book_language_select_title": "выбрать",
    "edit_book_language_rus_title": "русский",
    "edit_book_language_ukr_title": "украинский",
    "edit_book_language_eng_title": "английский",
    "edit_book_language_oth_title": "другой",

    "edit_book_cover_title": "Обложка",
    "edit_book_select_cover_title": "выбрать",
    "edit_book_select_hard_title": "твёрдая",
    "edit_book_select_soft_title": "мягкая",

    "edit_book_illustrations_title": "Иллюстрации",
    "edit_book_select_illustrations_title": "выбрать",
    "edit_book_select_illustrations_no_title": "нет",
    "edit_book_select_illustrations_bw_title": "чёрно-белые",
    "edit_book_select_illustrations_color_title": "цветные",

    "edit_book_age_group_title": "Возрастная группа",
    "edit_book_select_age_title": "выбрать",
    "edit_book_select_age_baby_title": "малыши",
    "edit_book_select_age_preschool_title": "дошкольники",
    "edit_book_select_age_junior_title": "младшие школьники",
    "edit_book_select_age_midschool_title": "подростки",
    "edit_book_select_age_adult_title": "взрослые",

    "edit_book_description_title": "Описание",
    "edit_book_images_description_title": "Рекомендуем добавить обложку, страницу с иллюстрацией, страницу с текстом и несколько, которые вам нравятся.",
    "edit_fileButton": "Добавить фото",
    "edit_book_close_title": "Закрыть",
    "edit_book_button_title": "Сохранить",

    "message_close_button_title": "Закрыть",

    "delete_book_modal_title_title": "Удалить книгу",
    "delete_book_modal_body_title": "Вы точно хотите удалить ",
    "delete_book_close_title": "Закрыть",
    "delete_book_delete_title": "Удалить",

    "image_close_button_title": "Закрыть",
    "image_preview_modal_title": "Просмотр фотографии",
    "image_close_button_footer_title": "Закрыть",

    "profile_name_title": "Имя ",
    "profile_surname_title": "Фамилия",
    "profile_book_to_the_moon_title": "Книга, которую вы бы взяли с собой на Марс",
    "profile_hero_title": "Любимый герой",
    "profile_year_title": "Год рождения",
    "profile_gender_title": "Пол",
    "profile_gender_select_title": "выбрать",
    "profile_gender_female_title": "женский",
    "profile_gender_male_title": "мужской",
    "profile_super_power_title": "Супер-сила",
    "profile_book_of_the_year_title": "Книги, впечатлившие вас в последнее время",
    "profile_hobby_title": "Что вы делаете, когда нечего читать",
    "profile_country_title": "Страна",
    "profile_city_title": "Город",
    "profile_city_set_me_title": "укажите, пожалуйста",
    "profile_district_title": "Район",
    "profile_fb_title": "Facebook",
    "open_title": "открыть",
    "profile_telegram_title": "Telegram",
    "profile_viber_title": "Viber",
    "profile_update_button_title": "Обновить",
    "profile_has_been_updated_title": "Изменения профиля были успешно сохранены.",
    "profile_update_server_error_title": "Изменить профиль не получилось из-за ошибки сервера.",
    "profile_update_auth_error_title": "Изменить профиль не получилось из-за ошибки аутентификации.",

    "emailCannotBeEmpty_title": "Email не может быть пустым.",
    "passwordCannotBeEmpty_title": "Пароль не может быть пустым.",
    "nameCannotBeEmpty_title": "Имя не может быть пустым.",
    "readerWithEmail_title": "Читатель с email-ом ",
    "singleNotFound_title": " не находится.",
    "incorrectPassword_title": "Неверный пароль для читателя с email-ом ",

    "readerDetailsWithId_title": "Данные читателя с id ",
    "cannotBeFound_title": " не находятся.",
    "noneFriendYet_title": "Пока что вы никого не добавили в друзья. Нажмите на иконку ",
    "iconNextToReader_title": " около читателя, которого вы хотите добавить в друзья.",
    "isAlreadyFriendOf_title": " уже друг ",
    "hasBeenAddedToFriends": " теперь ваш друг.",
    "isNotAFriendOf_title": " не является другом ",
    "reader_title": "Читатель ",
    "hasBeenRemovedFromFriends": " был удалён из друзей.",
    "noReaderWasFound_title": "По вашему запросу не было найдено ни одного читателя. Попробуйте смягчить критерии поиска.",

    "cannotBeAdded_title": " не может быть добавлена.",
    "cannotBeEdited_title": " не может быть изменена.",
    "cannotBeCreated_title": " не может быть создан.",
    "noBookWasFound_title": "По вашему запросу не было найдено ни одной книги. Попробуйте смягчить критерии поиска.",
    "goodDayToStartAddingBooks_title": "Сегодня - отличный день для того, чтобы начать добавлять книги.",
    "addingImageProblem_title": "Фотографию нельзя добавить из-за ошибки сервера. Максимальный размер файла - 20 Мб.",
    "addingImageAuthProblem_title": "Фотографию нельзя добавить из-за ошибки аутентификации.",
    "updatingImageProblem_title": "Фотографии нельзя изменить из-за ошибки сервера. Максимальный размер всех файлов - 100 Мб.",
    "updatingImageAuthProblem_title": "Фотографии нельзя изменить из-за ошибки аутентификации.",

    "hasBeenDeleted_title": " была успешно удалена.",
    "hasBeenAdded_title": " была успешно добавлена.",
    "hasBeenEdited_title": " была успешно отредактирована.",
    "hasBeenCreated_title": " был успешно создан.",
    "hasBeenSetActive_title": " теперь активна.",
    "hasBeenSetInactive_title": " теперь неактивна.",

    "details_edit_book_button_title": "Редактировать",
    "details_set_inactive_button_title": "Деактивировать",
    "details_set_active_button_title": "Активировать",
    "details_delete_button_title": "Удалить",
    "details_inactive_title": "НЕАКТИВНАЯ",
    "details_publisher_title": "Издательство: ",
    "details_language_title": "Язык: ",
    "details_year_title": "Год: ",
    "details_cover_title": "Обложка: ",
    "details_illustrations_title": "Иллюстрации: ",
    "details_ageGroup_title": "Возраст: ",
    "details_pages_title": "Страниц: ",
    "details_description_title": "Описание: ",
    "details_owner_title": "Хозяин: ",

    "search_book_title_title": "Название",
    "search_book_author_name_title": "Имя автора",
    "search_book_author_surname_title": "Фамилия автора",
    "search_book_city_title": "Город",
    "search_book_age_from_title": "От возрастной группы",
    "search_book_age_to_title": "До возрастной группы",
    "search_book_year_from_title": "От года",
    "search_book_year_to_title": "До года",
    "search_button_title": "Искать",
    "doNotDelete_warning_title": "Если вы не хотите, чтобы другие читатели видели эту книгу, достаточно её деактивировать.",
    "doYouStillWantToDelete_title": "Всё равно хотите удалить ",
    "book_title": "Книга ",

    "recent_title": "Недавние"
}

let ua = {
    "menu_add_book_title": "Додати книгу",
    "menu_my_books_title": "Мої книги",
    "menu_books_title": "Книги",
    "menu_readers_title": "Читачі",
    "menu_favorite_title": "Улюблені",
    "menu_favorite_readers_title": "Читачі",
    "favorite_readers_title": "Улюблені читачі",
    "logo_title": "Бубук",
    "add_reader_to_favorites_title": "Додати читача до улюблених",
    "remove_reader_from_favorites_title": "Прибрати читача з улюблених",
    "send_message_title": "Написати повідомлення",

    "register_page_title": "Бубук - Реєстрацiя",
    "register_form_title": "Створити акаунт",
    "register_name_title": "Им'я",
    "register_email_title": "Електронная пошта",
    "register_password_title": "Пароль",
    "register_register_button_title": "Створити",
    "register_login_button_title": "Увiйти",
    "register_close_title": "Закрити",

    "login_page_title": "Бубук - Вхiд",
    "login_login_form_title": "Вхiд",
    "login_email_title": "Електронна пошта",
    "login_password_title": "Пароль",
    "login_register_button_title": "Створити",
    "login_login_button_title": "Увiйти",

    "cabinet_page_title": "Бубук - Кабiнет читача",
    "chat_title": "Повідомлення",
    "profile_title": "Мій профіль",
    "logout_title": "Вийти",

    "add_book_title": "Додати книгу",
    "book_title_title": "Назва ",
    "author_name_title": "Ім'я автора ",
    "author_surname_title": "Прізвище автора ",
    "publisher_title": "Видавництво",
    "year_title": "Рік",
    "pages_quantity_title": "Сторінок",

    "language_title": "Мова",
    "language_select_title": "обрати",
    "language_rus_title": "росiйська",
    "language_ukr_title": "українська",
    "language_eng_title": "англійська",
    "language_oth_title": "iнша",

    "cover_title": "Обкладинка",
    "select_cover_title": "обрати",
    "select_hard_title": "тверда",
    "select_soft_title": "м'яка",

    "illustrations_title": "Ілюстрації",
    "select_illustrations_title": "обрати",
    "select_illustrations_no_title": "вiдсутнi",
    "select_illustrations_bw_title": "чорно-бiлi",
    "select_illustrations_color_title": "кольоровi",

    "age_group_title": "Вікова категорія",
    "select_age_title": "обрати",
    "select_age_baby_title": "малюки",
    "select_age_preschool_title": "дошкільнята",
    "select_age_junior_title": "молодші школярі",
    "select_age_midschool_title": "пiдлiтки",
    "select_age_adult_title": "дорослі",

    "description_title": "Опис",
    "images_description_title": "Радимо додати обкладинку, сторiнку з iлюстрацiєю, сторiнку з текстом та декiлька, що вам до вподоби.",
    "fileButton": "Додати фото",
    "add_book_close_title": "Закрити",
    "add_book_button_title": "Додати книгу",

    "edit_book_modal_title": "Редагувати книгу",
    "edit_book_title_title": "Назва ",
    "edit_book_active_title": "Активна",
    "edit_book_active_yes": "так",
    "edit_book_active_no": "нi",

    "edit_book_author_name_title": "Ім'я автора ",
    "edit_book_author_surname_title": "Прізвище автора ",
    "edit_book_publisher_title": "Видавництво",
    "edit_book_year_title": "Рік",
    "edit_book_pages_quantity_title": "Сторінок",

    "edit_book_language_title": "Мова",
    "edit_book_language_select_title": "обрати",
    "edit_book_language_rus_title": "росiйська",
    "edit_book_language_ukr_title": "українська",
    "edit_book_language_eng_title": "англійська",
    "edit_book_language_oth_title": "iнша",

    "edit_book_cover_title": "Обкладинка",
    "edit_book_select_cover_title": "обрати",
    "edit_book_select_hard_title": "тверда",
    "edit_book_select_soft_title": "м'яка",

    "edit_book_illustrations_title": "Ілюстрації",
    "edit_book_select_illustrations_title": "обрати",
    "edit_book_select_illustrations_no_title": "вiдсутнi",
    "edit_book_select_illustrations_bw_title": "чорно-бiлi",
    "edit_book_select_illustrations_color_title": "кольоровi",

    "edit_book_age_group_title": "Вікова категорія",
    "edit_book_select_age_title": "обрати",
    "edit_book_select_age_baby_title": "малюки",
    "edit_book_select_age_preschool_title": "дошкільнята",
    "edit_book_select_age_junior_title": "молодші школярі",
    "edit_book_select_age_midschool_title": "пiдлiтки",
    "edit_book_select_age_adult_title": "дорослі",

    "edit_book_description_title": "Опис",
    "edit_book_images_description_title": "Радимо додати обкладинку, сторiнку з iлюстрацiєю, сторiнку з текстом та декiлька, що вам до вподоби.",
    "edit_fileButton": "Додати фото",
    "edit_book_close_title": "Закрити",
    "edit_book_button_title": "Зберегти",

    "message_close_button_title": "Закрити",

    "delete_book_modal_title_title": "Видалити книгу",
    "delete_book_modal_body_title": "Ви точно хочете видалити ",
    "delete_book_close_title": "Закрити",
    "delete_book_delete_title": "Видалити",

    "image_close_button_title": "Закрити",
    "image_preview_modal_title": "Перегляд фотографії",
    "image_close_button_footer_title": "Закрити",

    "profile_name_title": "Ім'я ",
    "profile_surname_title": "Прізвище",
    "profile_book_to_the_moon_title": "Книга, що ви б її взяли з собою на Марс",
    "profile_hero_title": "Улюблений герой",
    "profile_year_title": "Рік народження",
    "profile_gender_title": "Стать",
    "profile_gender_select_title": "обрати",
    "profile_gender_female_title": "жіноча",
    "profile_gender_male_title": "чоловіча",
    "profile_super_power_title": "Супер-сила",
    "profile_book_of_the_year_title": "Книги, що вас найбільше вразили останнім часом",
    "profile_hobby_title": "Що ви робите, коли нема чого читати",
    "profile_country_title": "Країна",
    "profile_city_title": "Місто",
    "profile_city_set_me_title": "зазначте, будь ласка",
    "profile_district_title": "Район",
    "profile_fb_title": "Facebook",
    "open_title": "вiдкрити",
    "profile_telegram_title": "Telegram",
    "profile_viber_title": "Viber",
    "profile_update_button_title": "Поновити",
    "profile_has_been_updated_title": "Зміни профіля успішно збережені.",
    "profile_update_server_error_title": "Профіль не можна змінити через помилку сервера.",
    "profile_update_auth_error_title": "Профіль не можна змінити через помилку автентифікації.",

    "emailCannotBeEmpty_title": "Email не може бути вiдсутнiм.",
    "passwordCannotBeEmpty_title": "Пароль не може бути вiдсутнiм.",
    "nameCannotBeEmpty_title": "Iм'я не може бути вiдсутнiм.",
    "readerWithEmail_title": "Читач з email-ом ",
    "singleNotFound_title": " не знаходиться.",
    "incorrectPassword_title": "Невірний пароль для читача з email-ом ",

    "readerDetailsWithId_title": "Вiдомостi користувача з id ",
    "cannotBeFound_title": " не можуть бути знайденi.",
    "noneFriendYet_title": "Наразі ви не додали в друзі нікого. Тицьніть іконку ",
    "iconNextToReader_title": " біля читача, якого хочете додати в друзі.",
    "isAlreadyFriendOf_title": " вже є другом ",
    "hasBeenAddedToFriends": " було успішно додано в друзі.",
    "isNotAFriendOf_title": " не є другом ",
    "reader_title": "Читача ",
    "hasBeenRemovedFromFriends": " було успішно видалено з друзів.",
    "noReaderWasFound_title": "За вашим запитом не було знайдено жодного читача. Спробуйте пом'якшити критерії.",

    "hasBeenCreated_title": " був успішно створений.",
    "hasBeenAdded_title": " була успішно додана.",
    "hasBeenEdited_title": " була успішно змінена.",
    "hasBeenDeleted_title": " була успішно видалена.",
    "hasBeenSetActive_title": " наразі активна.",
    "hasBeenSetInactive_title": " наразі неактивна.",
    "cannotBeAdded_title": " не може бути доданою.",
    "cannotBeEdited_title": " не може бути зміненою.",
    "cannotBeCreated_title": " не може бути створеним.",
    "addingImageProblem_title": "Фотографiю не можна додати через помилку сервера. Максимальний розмір файла - 20 Мб.",
    "addingImageAuthProblem_title": "Фотографiю не можна додати через помилку автентифiкацiї.",
    "noBookWasFound_title": "За вашим запитом не було знайдено жодної книги. Спробуйте пом'ягшити критерії.",
    "updatingImageProblem_title": "Фотографiї не можна додати через помилку сервера. Максимальний розмір всіх файлів - 100 Мб.",
    "updatingImageAuthProblem_title": "Фотографiї не можна додати через помилку автентифiкацiї.",
    "goodDayToStartAddingBooks_title": "Сьогодні - чудовий день, аби почати додавати книжки",

    "details_edit_book_button_title": "Редагувати",
    "details_set_inactive_button_title": "Приховати",
    "details_set_active_button_title": "Активувати",
    "details_delete_button_title": "Видалити",
    "details_inactive_title": "НЕАКТИВНА",
    "details_publisher_title": "Видавництво: ",
    "details_language_title": "Мова: ",
    "details_year_title": "Рік: ",
    "details_cover_title": "Обкладинка: ",
    "details_illustrations_title": "Ілюстрації: ",
    "details_ageGroup_title": "Вік читача: ",
    "details_pages_title": "Сторінок: ",
    "details_description_title": "Опис: ",
    "details_owner_title": "Володар: ",

    "search_book_title_title": "Назва",
    "search_book_author_name_title": "Ім'я автора",
    "search_book_author_surname_title": "Прізвище автора",
    "search_book_city_title": "Місто",
    "search_book_age_from_title": "Від віку",
    "search_book_age_to_title": "До віку",
    "search_book_year_from_title": "Від року",
    "search_book_year_to_title": "До року",
    "search_button_title": "Шукати",
    "doNotDelete_warning_title": "Якщо ви не хочете, аби інші читачі бачили цю книгу, достатьо її деактивувати.",
    "doYouStillWantToDelete_title": "Все рівно хочете видалити ",
    "book_title": "Книга ",

    "recent_title": "Нещодавні"
}

let en = {
    "menu_add_book_title": "Add book",
    "menu_my_books_title": "My books",
    "menu_books_title": "Books",
    "menu_readers_title": "Readers",
    "menu_favorite_title": "Favorite",
    "menu_favorite_readers_title": "Readers",
    "favorite_readers_title": "Favorite Readers",
    "logo_title": "BooBook",
    "add_reader_to_favorites_title": "Add reader to favorites",
    "remove_reader_from_favorites_title": "Remove reader from favorites",
    "send_message_title": "Send a message",

    "register_page_title": "BooBook - Register Page",
    "register_form_title": "Create an account", //not
    "register_name_title": "First name",
    "register_email_title": "Email address",
    "register_password_title": "Password",
    "register_register_button_title": "Register",
    "register_login_button_title": "Login",
    "register_close_title": "Close",

    "login_page_title": "BooBook - Login Page",
    "login_login_form_title": "Login",
    "login_email_title": "Email address",
    "login_password_title": "Password",
    "login_register_button_title": "Register",
    "login_login_button_title": "Login",

    "cabinet_page_title": "BooBook - Reader's Cabinet",
    "chat_title": "Chat",
    "profile_title": "Profile",
    "logout_title": "Log Out",

    "add_book_title": "Add book",
    "book_title_title": "Title ",
    "author_name_title": "Author Name ",
    "author_surname_title": "Author Surname ",
    "publisher_title": "Publisher",
    "year_title": "Year",
    "pages_quantity_title": "Pages quantity",

    "language_title": "Language",
    "language_select_title": "select",
    "language_rus_title": "russian",
    "language_ukr_title": "ukrainian",
    "language_eng_title": "english",
    "language_oth_title": "other",

    "cover_title": "Cover",
    "select_cover_title": "select",
    "select_hard_title": "hard",
    "select_soft_title": "soft",

    "illustrations_title": "Illustrations",
    "select_illustrations_title": "select",
    "select_illustrations_no_title": "no",
    "select_illustrations_bw_title": "black & white",
    "select_illustrations_color_title": "color",

    "age_group_title": "Age group",
    "select_age_title": "select",
    "select_age_baby_title": "baby",
    "select_age_preschool_title": "preschool",
    "select_age_junior_title": "junior-school",
    "select_age_midschool_title": "mid-school",
    "select_age_adult_title": "adult",

    "description_title": "Description",
    "images_description_title": "Images are recommended to include: cover, one with text, one with illustration, and others you like",
    "fileButton": "Select images",
    "add_book_close_title": "Close",
    "add_book_button_title": "Add book",

    "edit_book_modal_title": "Edit book",
    "edit_book_title_title": "Title ",
    "edit_book_active_title": "Active",
    "edit_book_active_yes": "yes",
    "edit_book_active_no": "no",

    "edit_book_author_name_title": "Author Name ",
    "edit_book_author_surname_title": "Author Surname ",
    "edit_book_publisher_title": "Publisher",
    "edit_book_year_title": "Year",
    "edit_book_pages_quantity_title": "Pages quantity",

    "edit_book_language_title": "Language",
    "edit_book_language_select_title": "select",
    "edit_book_language_rus_title": "russian",
    "edit_book_language_ukr_title": "ukrainian",
    "edit_book_language_eng_title": "english",
    "edit_book_language_oth_title": "other",

    "edit_book_cover_title": "Cover",
    "edit_book_select_cover_title": "select",
    "edit_book_select_hard_title": "hard",
    "edit_book_select_soft_title": "soft",

    "edit_book_illustrations_title": "Illustrations",
    "edit_book_select_illustrations_title": "select",
    "edit_book_select_illustrations_no_title": "no",
    "edit_book_select_illustrations_bw_title": "black & white",
    "edit_book_select_illustrations_color_title": "color",

    "edit_book_age_group_title": "Age group",
    "edit_book_select_age_title": "select",
    "edit_book_select_age_baby_title": "baby",
    "edit_book_select_age_preschool_title": "preschool",
    "edit_book_select_age_junior_title": "junior-school",
    "edit_book_select_age_midschool_title": "mid-school",
    "edit_book_select_age_adult_title": "adult",

    "edit_book_description_title": "Description",
    "edit_book_images_description_title": "Images are recommended to include: cover, one with text, one with illustration, and others you like",
    "edit_fileButton": "Select images",
    "edit_book_close_title": "Close",
    "edit_book_button_title": "Save",

    "message_close_button_title": "Close",

    "delete_book_modal_title_title": "Delete book",
    "delete_book_modal_body_title": "Are you sure you want to proceed?",
    "delete_book_close_title": "Close",
    "delete_book_delete_title": "Delete",

    "image_close_button_title": "Close",
    "image_preview_modal_title": "Image preview",
    "image_close_button_footer_title": "Close",

    "profile_name_title": "Name ",
    "profile_surname_title": "Surname",
    "profile_book_to_the_moon_title": "Book you'd take to Mars",
    "profile_hero_title": "Hero you like",
    "profile_year_title": "Year of birth",
    "profile_gender_title": "Gender",
    "profile_gender_select_title": "select",
    "profile_gender_female_title": "female",
    "profile_gender_male_title": "male",
    "profile_super_power_title": "Super-power",
    "profile_book_of_the_year_title": "Most impressive books of the previous year",
    "profile_hobby_title": "What do you do when there's nothing to read",
    "profile_country_title": "Country",
    "profile_city_title": "City",
    "profile_city_set_me_title": "set me please",
    "profile_district_title": "District",
    "profile_fb_title": "Facebook",
    "open_title": "open",
    "profile_telegram_title": "Telegram",
    "profile_viber_title": "Viber",
    "profile_update_button_title": "Update",
    "profile_has_been_updated_title": "Profile data has been updated.",
    "profile_update_server_error_title": "When updating the reader info, there was a server error.",
    "profile_update_auth_error_title": "When updating the reader info, there was a problem with authentication.",

    "emailCannotBeEmpty_title": "Email cannot be empty.",
    "passwordCannotBeEmpty_title": "Password cannot be empty.",
    "nameCannotBeEmpty_title": "Name cannot be empty.",
    "readerWithEmail_title": "Reader with email ",
    "singleNotFound_title": " cannot be found.",
    "incorrectPassword_title": "Incorrect password for a reader with email ",

    "readerDetailsWithId_title": "Reader details for reader with id ",
    "cannotBeFound_title": " cannot be found.",
    "noneFriendYet_title": "None friend yet added yet. Click on ",
    "iconNextToReader_title": " icon next to a reader.",
    "isAlreadyFriendOf_title": " is already a friend of ",
    "hasBeenAddedToFriends": " has been successfully added to friends.",
    "isNotAFriendOf_title": " is not a friend of ",
    "reader_title": "Reader ",
    "hasBeenRemovedFromFriends": " has been successfully removed from friends.",
    "noReaderWasFound_title": "No reader fitting your criteria was found. Try to soften the borders.",

    "hasBeenDeleted_title": " has been deleted.",
    "hasBeenSetActive_title": " has been set active.",
    "hasBeenSetInactive_title": " has been set inactive.",
    "cannotBeEdited_title": " cannot be edited.",
    "cannotBeAdded_title": " cannot be added.",
    "cannotBeCreated_title": " cannot be created.",
    "hasBeenEdited_title": " has been successfully edited.",
    "hasBeenAdded_title": " has been successfully added.",
    "hasBeenCreated_title": " has been successfully created.",
    "noBookWasFound_title": "No book fitting your criteria was found. Try to soften the borders.",
    "goodDayToStartAddingBooks_title": "Today is a good day to start adding books.",
    "addingImageProblem_title": "Image cannot be added because of a server error. Maximum size of the file is 20Mb.",
    "addingImageAuthProblem_title": "Image cannot be added because of the problem with authentication.",
    "updatingImageProblem_title": "Images cannot be updated because of a server error. Maximum size of all images is 100Mb.",
    "updatingImageAuthProblem_title": "Images cannot be updated because of the problem with authentication.",

    "details_edit_book_button_title": "Edit",
    "details_set_inactive_button_title": "Set inactive",
    "details_set_active_button_title": "Set active",
    "details_delete_button_title": "Delete",
    "details_inactive_title": "INACTIVE",
    "details_publisher_title": "Publisher: ",
    "details_language_title": "Language: ",
    "details_year_title": "Year: ",
    "details_cover_title": "Cover: ",
    "details_illustrations_title": "Illustrations: ",
    "details_ageGroup_title": "Age group: ",
    "details_pages_title": "Pages: ",
    "details_description_title": "Description: ",
    "details_owner_title": "Owner: ",

    "search_book_title_title": "Title",
    "search_book_author_name_title": "Author name",
    "search_book_author_surname_title": "Author surname",
    "search_book_city_title": "City",
    "search_book_age_from_title": "Age group from",
    "search_book_age_to_title": "Age group to",
    "search_book_year_from_title": "Year from",
    "search_book_year_to_title": "Year to",
    "search_button_title": "Search",
    "doNotDelete_warning_title": "If you do not want others to see this book, you can make it Inactive.",
    "doYouStillWantToDelete_title": "Do you still want to delete book ",
    "book_title": "Book ",

    "recent_title": "Recent"
}


// let application_language = en;
